# synchronize the clock between Gazebo/Ros, send IMU and Lidar data to Ros

- ros_topic_name: "imu" #must be without / so that the namespace is used from the launch file (for all ros topics in this file)
  gz_topic_name: "/swerve_bot1/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "scan"
  gz_topic_name: "/swerve_bot1/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "scan/points"
  gz_topic_name: "/swerve_bot1/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

